version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:443"
    volumes:
      - ./website:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx/
      - ./not-the-news:/root/not-the-news

